### ISSUE TITLE
Access vba or caller in converter for UDFs

### ISSUE THREAD

**Issue by audetto** [xlwings/xlwings#1541] opened 2021-03-11 19:02 UTC
I would like to know if it is possible to access `vba` or `caller` inside a converter.

The use case is a function returning an object which is saved into a python dictionary and the key returned to Excel.
I would like to use the cell name to avoid constantly creating new objects.

I could do this inside the function, but I like the idea of the converter so that I keep this Excel logic separated. And when calling it from python, it does not alter the behaviour.

Moreover I could use a decorator around the function, but that would alter the normal python behaviour.

I really like the idea of the converters.

Any suggestion?

**Comment by fzumstein** [comment] 2021-03-12 08:06
If you could add an example, that would certainly help. Converters are only good for manipulating the values, but you might be able to pull something off by writing an Accessor. Since they are currently not documented, you could take a look at one here:
https://github.com/xlwings/xlwings/blob/master/xlwings/conversion/standard.py#L168-L182

**Comment by audetto** [comment] 2021-03-12 11:46
I will provide an example, but meanwhile I found a way to achieve it

```
excel = xw.apps.active
application = excel.api.Application
caller = excel.Caller

address = caller.Address
```

This works in converters, even if they don't have access to the ``caller`` provided by ``xw``.

**Comment by fzumstein** [comment] 2021-03-12 14:00
I'd rather use `xw.Book.caller().app` instead of `xw.app.active`

**Comment by audetto** [comment] 2021-03-12 18:49
here is an example

https://github.com/audetto/xlwings-demo/blob/master/main.py

in particular, https://github.com/audetto/xlwings-demo/blob/master/main.py#L16

With this technique, objects are never deleted.

The idea is almost the same as `get_cache_key` in https://github.com/xlwings/xlwings/blob/f72bc83c8d4e1578ab810e53a67e7873947bebf7/xlwings/udfs.py#L411

But with the suggestion above, once can bypass the whole `caller` thing. Are there any drawbacks?

**Comment by fzumstein** [comment] 2022-02-09 01:04
I am closing this as I think it's a dupe of #555.

**Closed by fzumstein** 2022-02-09 01:04 UTC
