### ISSUE TITLE
pywintypes.com_error: (-2147023266, '这个类型的数据不受支持。', None, None)

### ISSUE THREAD

**Issue by running1st** [xlwings/xlwings#1722] opened 2021-09-28 14:52 UTC
#### Describe your issue (incl. Traceback!)

```python
File "D:\Program Files\PythonProgram\practise_excel.py", line 3, in <module>
    app=xw.App(visible=True,add_book=False)
  File "D:\Program Files\python\lib\site-packages\xlwings\main.py", line 219, in __init__
    self.impl = xlplatform.App(spec=spec, add_book=add_book, visible=visible)
  File "D:\Program Files\python\lib\site-packages\xlwings\_xlwindows.py", line 317, in __init__
    self._xl = COMRetryObjectWrapper(DispatchEx('Excel.Application'))
  File "D:\Program Files\python\lib\site-packages\win32com\client\__init__.py", line 113, in DispatchEx
    dispatch = pythoncom.CoCreateInstanceEx(clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,))[0]
pywintypes.com_error: (-2147023266, '这个类型的数据不受支持。', None, None)

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import xlwings as xw
app=xw.App(visible=True,add_book=False)
```

**Comment by fzumstein** [comment] 2021-09-28 15:03
closing this as duplicate of  #1480

**Closed by fzumstein** 2021-09-28 15:03 UTC
