### ISSUE TITLE
macOS Sierra: Parsing of "#N/A" leads to inconsistencies and errors

### ISSUE THREAD

**Issue by Bernouilly** [xlwings/xlwings#1188] opened 2019-11-26 16:13 UTC
[demo.xlsx](https://github.com/xlwings/xlwings/files/3892778/demo.xlsx)

#### Parsing of "#N/A" leads to inconsistencies and errors

```python

>python report.py
First parsing
[[1.0, 2.0], [3.0, 4.0], [None, None], [None, None]]
Second parsing
[[1.0, 2.0], [3.0, 4.0], [None, None], [None, None]]
The last line comprised of #N/A is lacking
third parsing
Traceback (most recent call last):
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 74, in send
    replyevent = self._sendproc(self.AEM_event, flags, timeout)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 23, in sendappleevent
    return evt.send(flags, timeout)
aem.ae.MacOSError: -609
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 482, in __call__
    return self.AS_appdata.target().event(self._code, params, atts, codecs=self.AS_appdata).send(timeout, sendflags)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/aeosa/aem/aemsend.py", line 77, in send
    raise EventError(err.args[0]) from err
aem.aemsend.EventError: Command failed: Connection is invalid. (-609)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "report.py", line 14, in <module>
    print(book.sheets['foo'].range((1,1), (5,3)).value)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/main.py", line 1524, in value
    return conversion.read(self, None, self._options)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/conversion/__init__.py", line 27, in read
    pipeline(ctx)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/conversion/framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/conversion/standard.py", line 70, in __call__
    c.value = c.range.raw_value
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/main.py", line 1145, in raw_value
    return self.impl.raw_value
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/xlwings/_xlmac.py", line 475, in raw_value
    return self.xl.value.get()
  File "/Users/nv5375/miniconda3/lib/python3.7/site-packages/aeosa/appscript/reference.py", line 518, in __call__
    raise CommandError(self, (args, kargs), e, self.AS_appdata) from e
appscript.reference.CommandError: Command failed:
        OSERROR: -609
        MESSAGE: Connection is invalid.
        COMMAND: app(pid=23905).workbooks[1].worksheets['foo'].cells['$A$1:$C$5'].value.get()
```

```python

import xlwings as xw
​
book = xw.Book('demo.xlsx')
​
​
print('First parsing')
print(book.sheets['foo'].range((1,1), (4,2)).value)
​
print('Second parsing')
print(book.sheets['foo'].range((1,1), (5,2)).value)
print('The last line comprised of #N/A is lacking')
​
print('third parsing')
print(book.sheets['foo'].range((1,1), (5,3)).value
```

**Comment by fzumstein** [comment] 2019-11-26 16:27
duplicate of #1028 ?

**Comment by Bernouilly** [comment] 2019-11-26 16:43
Seems to be, indeed!

**Comment by Bernouilly** [comment] 2019-11-26 16:43
Seems to be, indeed!

**Closed** 2019-12-02 13:18 UTC
