### ISSUE TITLE
No error message when sheet name longer than 31 characters for .copy()

### ISSUE THREAD

**Issue by EthanTheMathmo** [xlwings/xlwings#1762] opened 2021-11-07 17:53 UTC
#### 
When using the .copy method, e.g.
`sheet.copy(before=None, after=None, name=new_name) ` 

if the `name` variable is longer than 31 characters, instead of providing an error message, a blue wheel appears and flickers indefinitely. The source of the problem seems to be Excel allowing sheet names only to be 31 characters long. It'd be helpful if this appeared as an error message rather than breaking the program. 

(workaround is quite simple: when creating the names dynamically I just add a `[:31]`, but someone was unaware of the excel sheet character limit it might be quite confusing)

**Comment by fzumstein** [comment] 2021-11-07 17:56
Duplicate of https://github.com/xlwings/xlwings/issues/1725 and fixed in 0.25.0

**Closed by fzumstein** 2021-11-07 17:56 UTC
