### ISSUE TITLE
Efficient serialization of object instances

### ISSUE THREAD

**Issue by vantessel** [xlwings/xlwings#1959] opened 2022-07-11 19:57 UTC
#### Problem
Currently `xlwings` forces a functional programming approach, whereby object instances can't be passed across UDF calls. For example let's take a simple case:

```python
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    @classmethod
    def new(cls):
        return cls.__new__(cls)

    @property
    def norm(self):
        return (self.x**2 + self.y**2) ** 0.5

    def translate(self, tau):
        self.x += tau
        self.y += tau
```

assuming I wanted to call the `norm` method from the spreadsheet, the UDF would have to look like this:

```python
@xw.func
def norm(x, y):
    p = Point(x, y)
    return p.norm
```

this is OK for simple objects/arguments, but forces you to re-instantiate the object at each function call. If the object instance were to contain some intermediate values, then we would be effectively forced to recompute them with each call, with significant overhead. 

#### A (Weak) Solution
We can attempt to solve the point above by passing the attribute dictionary from the UDF, and either overring the `__dict__` of the object or implementing some `to_dict()` and `from_dict()` methods. Then the UDF would look like this:

```python
@xw.func
@xw.arg("point_data", dict)
def norm(point_data):
    p = Point.new()
    p.__dict__ = point_data
    return p.norm
```

and return the dictionaries of object instances like so:

```python
@xw.func
@xw.arg("point_data", dict)
def translate(point_data, tau):
    p = Point.new()
    p.__dict__ = point_data
    p.translate(tau)
    return p.__dict__
```

![image](https://user-images.githubusercontent.com/19397409/178344193-db6c335f-f47e-4686-95cf-a108ab49e676.png)

The issue with this solution is that it's impractical for large objects and creates issues of data consistency and reliability. 

#### A better solution
A better solution would probably be to use the Custom Converters that are made [available](https://docs.xlwings.org/en/stable/converters.html#custom-converter) by `xlwings`. This however requires to write a custom converter for each object, and requires some analysis to find a good serialization format (especially for large objects).

#### Can we do better?
I think it would be far better if `xlwings` came with an out-of-the-box object serialization format. In particular this could be either a simple serialization, or even better, some type of pointer representing a specific object instance, which can then be passed to a function call directly. This could be for example a string which points to some instances table stored somewhere

The above could then look like this:

```python
@xw.func
@xw.arg("p", Point)
def new_norm(p):
    return p.norm

@xw.func
@xw.arg("p", Point)
def new_translate(p, tau):
    p.translate(tau)
    return p
```

![image](https://user-images.githubusercontent.com/19397409/178346996-72a0957f-bf5f-4062-9250-f36207d0bbb8.png)

A final extension of this could be to create a full-fledged spreadsheet class support eg through `@xw.class` or some class inheritance, such that class methods become automatically converted to UDFs and we can then call directly from the spreadsheet `=Point.norm(point_reference)`  and `=Point.translate(point_reference, tau)` without having to wrap up the class methods with `@xw.func`

**Comment by fzumstein** [comment] 2022-07-12 07:12
I think this is a duplicate of https://github.com/xlwings/xlwings/issues/555

**Comment by fzumstein** [comment] 2023-01-18 19:55
closing because of duplicate, also you might find what you want here: https://github.com/cunnane/xloil

**Closed by fzumstein** 2023-01-18 19:55 UTC
