### ISSUE TITLE
How to use class.functionName to call udf in excel?

### ISSUE THREAD

**Issue by phpsxg** [xlwings/xlwings#1938] opened 2022-06-20 09:01 UTC
#### OS 
Windows 10
#### Versions of xlwings, Excel and Python
 0.27.9, Office 365, Python 3.8
#### Describe your issue 
 I can use functionName to call udf in excel, but how to use class.functionName to call udf in excel?
```python
import xlwings as xw


@xw.func
def hello(name):
    return f'hello, {name}'


```python
I can enter =test() in excel to execute，how to use Demo.test() to execute?
```

import xlwings as xw

class Demo:
    @xw.func
    def hello(name):
        return f'hello, {name}'

```
**I tried it, it doesn't work this way**

**Comment by fzumstein** [comment] 2022-06-20 09:19
This is a dupe of https://github.com/xlwings/xlwings/issues/1301 xlwings doesn't support class methods directly, so you'd have to wrap them in regular functions.

**Closed by fzumstein** 2022-06-20 09:19 UTC
