### ISSUE TITLE
xlwings addin crashes large Excel files opened from network drive

### ISSUE THREAD

**Issue by denfromufa** [xlwings/xlwings#649] opened 2017-04-04 20:35 UTC
Files larger than ~40MB crash Excel when opened from network drive.

Excel 2016 32-bit, Windows 7 64-bit 

```
C:\Users\denis.akhiyarov>python
Python 2.7.13 |Anaconda custom (32-bit)| (default, Dec 19 2016, 13:36:02) [MSC v
.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import xlwings
>>> xlwings.__version__
'0.10.4'
```

Removing the addin or copying the Excel files to local drive resolves the crashes.

**Comment by denfromufa** [comment] 2017-04-04 20:49
On another machine with UAC ON, the same procedure just stalled Excel - even `taskkill /f /im Excel*` does not kill Excel.

**Comment by denfromufa** [comment] 2017-04-06 15:30
@fzumstein note that the issue is not reproducible with Excel 2010. So this maybe deeper somewhere in comtypes or pywin32 or COM interop with Excel.

**Comment by denfromufa** [comment] 2017-04-06 15:51
The file opens fine if first Excel is opened and then the file is loaded. The crash happens only when opening the file before Excel is loaded.

**Comment by fzumstein** [comment] 2017-04-06 17:05
I am currently rewriting the addin, I would suggest we take it up again when it's out to see if the error persists...

**Comment by denfromufa** [comment] 2017-04-27 23:06
More update on the problem - if ".py" filename with the workbook name does not exist, then the crash happens! if the ".py" is present - no crash.

**Comment by fzumstein** [comment] 2017-04-28 06:35
so is it unrelated to the workbooks size or network location?

**Comment by denfromufa** [comment] 2017-04-28 14:36
@fzumstein i deleted my previous comment, the existence of .py file changes nothing. so still crashes from network drive.

**Comment by fzumstein** [comment] 2020-05-20 15:59
closing this as I couldn't reproduce

**Closed by fzumstein** 2020-05-20 15:59 UTC
Labels: bug
