### ISSUE TITLE
Syntax error RunPython using xlwings, sys.path

### ISSUE THREAD

**Issue by mrizqinurkhalish** [xlwings/xlwings#1313] opened 2020-05-18 03:14 UTC
OS Windows 10 Pro

Versions of xlwings, Excel, and Python (0.9.0, Office 365, Python 3.8.2)

I am new on using xlwings through VBA. I run the exact syntax from a tutorial webpage on both VBA and Python, but it gives error like this:

![image](https://user-images.githubusercontent.com/61173217/82170907-fd26b700-98ef-11ea-8a12-13aa740551bd.png)

I used original syntax for VBA, and the syntax I used for python is like this:
```python

import xlwings as xw

#@xw.sub  # only required if you want to import it or run it via UDF Server
def main():
    wb = xw.Book.caller()
    wb.sheets[0].range("A1").value = "Hello xlwings!"

#@xw.func
def hello(name):
    return "hello {0}".format(name)

if __name__ == "__main__":
    xw.Book("Trial2.xlsm").set_mock_caller()
    main()


```

I barely find any clue for this problem, so I'm hoping that someone can give me a solution

**Comment by fzumstein** [comment] 2020-05-18 07:19
Based on https://stackoverflow.com/questions/61862083/syntax-error-runpython-using-xlwings-sys-path you may have a backslash somewhere in your config that shouldn't be there. Can you paste your config (whatever you have in the addin) or in the `C:\Users\<user>\.xlwings\xlwings.conf` file?

**Comment by MasterShake20** [comment] 2020-11-13 15:45
Having the same problem.  Not even able to run the default hello function from excel because of this error.  It works however if I run it from python.  I don't know where to go to fix this.

**Comment by fzumstein** [comment] 2020-11-13 15:49
Can you please provide the content of your config file as per previous answer?

**Comment by seek2fly** [comment] 2021-11-26 21:51
I am commenting about my experience with the same problem. 
The cause for me was that my **project name contained a hyphen**: 

To reproduce: 
Created a project using "xlwings quickstart MyProject-ABC"
Open excel file.
In xlwings menu, click "Run Main"
This causes the error.

To fix, remove hyphens: 
Renaming the excel file to MyProjectABC.xlsm and renaming the python file to MyProjectABC.py **solved the problem**

Note: Using a hyphen in the name of the parent folder does not appear to be a problem in my situation, just the file names.
Hoping this helps fix the code in RunPython

**Comment by fzumstein** [comment] 2021-11-27 09:08
Thanks for your input @seek2fly, and yes, xlwings should check for valid Python module names during the `quickstart` command. The name of the Excel file can always be changed later on (together with the RunPython command). I am closing this in favor of https://github.com/xlwings/xlwings/issues/1773.

**Closed by fzumstein** 2021-11-27 09:08 UTC
