### ISSUE TITLE
Feature request: Apply custom `Converter` inside `list`s and `DataFrame`s.

### ISSUE THREAD

**Issue by rudolfbyker** [xlwings/xlwings#2170] opened 2023-02-21 08:51 UTC
#### OS (e.g. Windows 10 or macOS Sierra)

Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)

- xlwings 0.29.1
- Office 365
- Python 3.9

#### Description

I can apply my custom `Converter` when writing one value at a time, but not when writing multiple. I have tried using a `list`, `list-of-lists`, and `DataFrame`.

#### Sample code

```python
from dataclasses import dataclass
from typing import Any, Dict

from xlwings import Book, Range
from xlwings.conversion import Converter


@dataclass
class Animal:
    sound: str
    name: str


class AnimalConverter(Converter):
    @staticmethod
    def read_value(value: Any, options: Dict[str, Any]) -> Any:
        raise NotImplementedError()

    @staticmethod
    def write_value(value: Any, options: Dict[str, Any]) -> str:
        if not isinstance(value, Animal):
            raise ValueError(f"Expected `Animal`, got `{type(value)!r}`.")

        return f"{value.name}: {value.sound}"


if __name__ == '__main__':
    AnimalConverter.register(Animal)
    wb = Book()
    try:
        # This works
        r = Range("A1")
        r.value = Animal(sound="bok-bok-bok", name="Chicken")
        print(r.value)

        # This fails with `TypeError: must be real number, not Animal`.
        # The same happens when my value is inside a `DataFrame`.
        r = Range("A1:A3")
        r.value = [
            Animal(sound="bok-bok-bok", name="Chicken"),
            Animal(sound="moo", name="Cow"),
            Animal(sound="quack", name="Duck"),
        ]
        print(r.value)
    finally:
        wb.close()
```

#### Traceback

```python
Traceback (most recent call last):
  File "C:\…\demo.py", line 38, in <module>
    r.value = [
  File "C:\…\venv\lib\site-packages\xlwings\main.py", line 2395, in value
    conversion.write(data, self, self._options)
  File "C:\…\venv\lib\site-packages\xlwings\conversion\__init__.py", line 102, in write
    pipeline(ctx)
  File "C:\…\venv\lib\site-packages\xlwings\conversion\framework.py", line 76, in __call__
    stage(*args, **kwargs)
  File "C:\…\venv\lib\site-packages\xlwings\conversion\standard.py", line 75, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "C:\…\venv\lib\site-packages\xlwings\conversion\standard.py", line 63, in _write_value
    rng.raw_value = value
  File "C:\…\venv\lib\site-packages\xlwings\main.py", line 1957, in raw_value
    self.impl.raw_value = data
  File "C:\…\venv\lib\site-packages\xlwings\_xlwindows.py", line 1161, in raw_value
    self.xl.Value = data
  File "C:\…\venv\lib\site-packages\xlwings\_xlwindows.py", line 148, in __setattr__
    return setattr(self._inner, key, value)
  File "C:\…\venv\lib\site-packages\win32com\client\__init__.py", line 595, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
TypeError: must be real number, not Animal
```

**Comment by fzumstein** [comment] 2023-02-21 10:38
This is a duplicate of https://github.com/xlwings/xlwings/issues/868 and while I get the idea, it's not something I consider implementing soon. The solution described in https://github.com/xlwings/xlwings/issues/868 should be good enough (you simply have to explicitly specify your converter). Maybe in a distant future, this whole thing can be refactored to use Pydantic and then it might be worth reconsidering. In the meantime I am going to close this.

**Closed by fzumstein** 2023-02-21 10:38 UTC

**Comment by rudolfbyker** [comment] 2023-02-22 06:15
> you simply have to explicitly specify your converter

The problem is that it's not that simple in all codebases. There may be many different places where values are written, and those places may be inside a dependency or even a transitive dependency, i.e. a place where we don't have the opportunity to inject an argument into `options()`.

Example:
- Library A depends on Library B, depends on xlwings.
- Library A (my code) defines these custom classes, which should be converted to values on the cell level.
- Library B uses xlwings to do stuff like `range.options(…).value = …`
- I need to register the Converter in Library A, either because
  - I don't have jurisdiction over library B, or
  - good separation of concerns requires that it is done in library A, rather than library B.

**Comment by rudolfbyker** [comment] 2023-02-22 06:17
By the way, would you close issues as "not planned" rather than "completed", when applicable? It's less confusing to users who search through the issues later.
