### ISSUE TITLE
Import UDF is not working in excel 2010

### ISSUE THREAD

**Issue by ddontham** [xlwings/xlwings#1430] opened 2020-10-08 03:43 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
Windows
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings version is 0.20.7
MS Office 2010
Python 3.8

#### Describe your issue (incl. Traceback!)

I installed xlwings using below commands. i created a simple user defined function and try to import in excel and it is not working. it gives me below error

pip install xlwings

xlwings addin install 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

my code for udf
-------------------------------------
import xlwings as xw
import cx_Oracle

@xw.func
def DBQuery(sqlquery):
 cx_Oracle.init_oracle_client(lib_dir=r"D:\instaclient\instantclient_19_8")
 username = "RMSUSER"
 password = "test123"
 hostname = "192.168.2.175"
 servicename = "RMSDB"

 connectstring = hostname + ":1521/" + servicename

 #print(connectstring)

 connection = cx_Oracle.connect(username, password, connectstring, encoding="UTF-8")

 cursor = connection.cursor()

 cursor.execute(sqlquery)
 result=cursor.fetchall()
 connection.close()
 return (len(result))

screenshot`:
![image](https://user-images.githubusercontent.com/68939440/95412372-79c13d00-0946-11eb-868b-1d0a9d6a05c4.png)

**Comment by ddontham** [comment] 2020-10-08 06:52
python path in my system

![image](https://user-images.githubusercontent.com/68939440/95424398-2fe55080-0960-11eb-950b-2d61e934f35c.png)


if you observe the error it is taking pythonw.exe from c:\pythonw38 which actually doesn't exist in the system.. i don't know from where this is coming from

![image](https://user-images.githubusercontent.com/68939440/95424745-c31e8600-0960-11eb-95ae-4708a23489fd.png)

**Comment by ddontham** [comment] 2020-10-08 06:53
my local python installation

![image](https://user-images.githubusercontent.com/68939440/95424937-1c86b500-0961-11eb-8b09-43fd1095acc9.png)

**Comment by fzumstein** [comment] 2020-10-08 08:00
Sorry about that, it's a duplicate of https://github.com/xlwings/xlwings/issues/1421. Will try to get this sorted soon. In the meantime, use the workaround described there (activate `Show Console`).

**Closed by fzumstein** 2020-10-08 08:00 UTC
