### ISSUE TITLE
Writing the contents of a pandas DataFrame to an Excel ListObject has some quirks

### ISSUE THREAD

**Issue by rudolfbyker** [xlwings/xlwings#2383] opened 2024-01-17 11:56 UTC
## Versions

- Windows 10
- Excel 365
- xlwings 0.30.12
- Python 3.11

## Summary

When writing the contents of a pandas DataFrame to an Excel ListObject,
- We need to set the column names and the data separately, otherwise the ListObject disappears.
- When we set the data, columns that have a string starting with `=` in the first row will use that formula for ALL rows in the column, ignoring the rest of the data from the DataFrame.

(I don't have a big issue with the first point, but the second point is a blocker for me, since I have not found a performant workaround yet.)

## Example

```python
import xlwings as xw
import pandas as pd


def main() -> None:
    df = pd.DataFrame(
        {
            "Foo": [1, 2, 3],
            "Bar": ["=1", "=2", "=3"],
        }
    )
    wb = xw.Book()
    sheet = wb.sheets[0]

    lo_range = sheet.range("A1:B3")

    # Create ListObject.
    # See https://docs.microsoft.com/en-us/office/vba/api/excel.listobjects.add
    lo = sheet.api.ListObjects.Add(1, lo_range.api, None, 1)
    lo.Name = "Table1"
    lo_columns = [lo.ListColumns(i + 1) for i in range(lo.ListColumns.Count)]

    # We can't just do this, because it destroys the ListObject for some reason:
    # lo_range.options(index=False).value = df

    # Set column names.
    for column, name in zip(lo_columns, df.columns):
        column.Name = name

    # Set values. The second column is set incorrectly.
    lo_range.offset(row_offset=1).options(index=False, header=False).value = df

    # This works just fine.
    normal_range = sheet.range("D1:E3")
    normal_range.options(index=False).value = df


if __name__ == "__main__":
    main()
```

Actual output:

![image](https://github.com/xlwings/xlwings/assets/10025342/9a64f7f6-97a1-467b-805c-c92397225307)

Expected output:

![image](https://github.com/xlwings/xlwings/assets/10025342/511bc95a-9828-435a-979f-043c11032bfb)

**Comment by fzumstein** [comment] 2024-01-17 12:51
You're looking for:
https://docs.xlwings.org/en/latest/api/table.html#xlwings.main.Table.update

**Comment by rudolfbyker** [comment] 2024-01-17 13:06
`Table.update` has the same problem:

```python
import xlwings as xw
import pandas as pd


def main() -> None:
    df = pd.DataFrame(
        {
            "Foo": [1, 2, 3],
            "Bar": ["=1", "=2", "=3"],
        }
    )
    wb = xw.Book()
    sheet = wb.sheets[0]

    lo_range = sheet.range("A1:B3")

    # Create ListObject.
    # See https://docs.microsoft.com/en-us/office/vba/api/excel.listobjects.add
    lo = sheet.api.ListObjects.Add(1, lo_range.api, None, 1)
    lo.Name = "Table1"

    # Update the ListObject. The second column is set incorrectly.
    table = wb.sheets[0].tables["Table1"]
    table.update(data=df, index=False)

    # This works just fine.
    normal_range = sheet.range("D1:E3")
    normal_range.options(index=False).value = df


if __name__ == "__main__":
    main()
```

Actual output:

![image](https://github.com/xlwings/xlwings/assets/10025342/9a64f7f6-97a1-467b-805c-c92397225307)

Expected output:

![image](https://github.com/xlwings/xlwings/assets/10025342/511bc95a-9828-435a-979f-043c11032bfb)

**Comment by fzumstein** [comment] 2024-01-17 13:29
* FYI: `sheet.api.ListObjects` is available natively via `sheet.Tables`.
* I've missed the other issue: in this case this is a duplicate of: https://github.com/xlwings/xlwings/issues/2113 and therefore I believe that this issue can be closed.

**Closed by fzumstein** 2024-01-17 13:29 UTC
