### ISSUE TITLE
Use of Autofilters

### ISSUE THREAD

**Issue by jvaldiviezo9** [xlwings/xlwings#1242] opened 2020-01-21 14:25 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
Python 3.7, xlwings: 0.15.10
#### Describe your issue (incl. Traceback!)
I'm currently facing an issue when using Excel as a "Viewer" for DataFrame Objects where I need to do some exploration on the information. In many cases, it's handy to override everything but keep the autofilter when refreshing the information. The issue is that seems like xlwings don't natively support filters. I'm looking for some workarounds about how to call the autofilter function directly from xlwings, I've found that with the "api" call from the object can help but I've not found documentation related.

Another option is if there is a way to connect with my personal macro workbook and call macros on demand from there.

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment] 2020-01-21 14:30
This looks like a duplicate of https://github.com/xlwings/xlwings/issues/679 to me, please continue there.

**Closed by fzumstein** 2020-01-21 14:30 UTC
