### ISSUE TITLE
BUG non adjacent selected cell

### ISSUE THREAD

**Issue by akasolace** [xlwings/xlwings#2270] opened 2023-05-25 15:07 UTC
Error when iterating though nonadjacent selected cell.

```python
    wb = xw.Book.caller()
    selectedCells = wb.app.selection 
    print(selectedCells) # <Range [PFC.xlsm]DE!$I$7,$AC$7>  (correct)
    for cell in selectedCells:
        print(cell.address)  # $I$7  $I$8    expects  $I$7  $AC$7  
```

looking on SO, I saw a post from 2016 referencing that issue and suggesting the following workaround that still work:
```python
    wb = xw.Book.caller()
    selectedCells = wb.app.selection 
    print(selectedCells) # <Range [PFC.xlsm]DE!$I$7,$AC$7>  (correct)
    for cell in selectedCells.api:
        print(cell. Valuess) # $I$7  $AC$7  
```

**Comment by fzumstein** [comment] 2023-05-26 09:13
xlwings currently doesn't support multi-region ranges, so this is a known issue. Closing this as it's a duplicate of https://github.com/xlwings/xlwings/issues/595

**Closed by fzumstein** 2023-05-26 09:13 UTC
