### ISSUE TITLE
xlwings.xlam (from xlwings 0.32.1) considered as malware by many antiviruses

### ISSUE THREAD

**Issue by gdementen** [xlwings/xlwings#2510] opened 2024-09-04 10:42 UTC
#### Describe your issue (incl. Traceback!)

Cannot install xlwings 0.32.1 (the latest version available from anaconda) on Windows 10 because SentinelOne (and 22 other anti-malware products !) flag it as malware:

See https://www.virustotal.com/gui/file/426bcd7c0bed86ce7ff13dc4de0bad1899650093d1f1e46fbba7c9b55564a9e9/detection

Version 0.31.4 (the previous version packaged by anaconda) installs fine.

I am unsure you can do anything about it but I thought you might want to know.

**Comment by gdementen** [comment] 2024-09-04 12:21
the .xlam file in the pypi packages (source and whl for 0.32.1) is the same than in the conda package but different from the one in the repository (which is flagged by much fewer antivirus -- https://www.virustotal.com/gui/file/ea2a9359a0c77146e3d6ff8ad392f6d348957ea11947e021a2b4862fbad98b4a). @fzumstein : any idea what could be causing this? I am getting nervous about this.

**Comment by gdementen** [comment] 2024-09-04 12:39
Ok, I suppose the file being different is to be expected because of the release process signature step at https://github.com/xlwings/xlwings/blob/6f26baf2f6f0da382c0e7e710ce3824003820f9b/.github/workflows/main.yml#L124

Now I wonder how I can check the signed file "source" is the same file as the repository/original file.

**Comment by fzumstein** [comment] 2024-09-04 19:37
* This is basically a dupe of https://github.com/xlwings/xlwings/issues/2254. The difference is simply the version string (dev vs 0.x.x) as the file gets "built" during the release action.
* False positives are annoying, but they come and go. For example, the latest version only shows 4 instead of 22 false positives: https://www.virustotal.com/gui/file/da28ee11985d8723910ecad0fbe350497392fd9610c148157c03416a65dce60d/detection
* via conda forge channel you'll always get the latest version
* Have a look at https://github.com/xlwings/xlwings-server, which gets rid of all these issues

**Comment by gdementen** [comment] 2024-09-06 08:12
Thanks for the answer and the various pointers. 

In my experience, mixing condaforge and the "defaults" anaconda channel is a recipe for disaster (random packages breaking in subtle ways and updates which flip-flops between channels for each update). Going full condaforge is not an option for us currently. We might get to it at some point, but we are not there yet.

If I understand correctly, xlwings-server is about using Python from Excel (right?), but we use xlwings to do the opposite (AFAIK, we don't even use the problematic addin). 

In any case, I would very much appreciate it, if you could you just confirm that the xlwings.xlam in the various packages on pypi for version 0.32.1 is actually what it's supposed to be/has not been tampered with. If that's the case, I will just ask our security provider to whitelist it. Thank you in advance.

**Comment by fzumstein** [comment] 2024-09-07 09:57
> If I understand correctly, xlwings-server is about using Python from Excel (right?)

correct, so not helpful in your case, unfortunately!

> In any case, I would very much appreciate it, if you could you just confirm that the xlwings.xlam in the various packages on pypi for version 0.32.1 is actually what it's supposed to be/has not been tampered with

If you or Anaconda suffered a man-in-the-middle attack when downloading from pypi, that won't help you. The only way to make sure is to open the file in Excel and go to the VBA editor > Tools > Digital Signature... and check that it is signed by Zoomer Analytics GmbH:

<img width="403" alt="Screenshot 2024-09-07 at 11 56 16 AM" src="https://github.com/user-attachments/assets/d72bec8f-a83f-4ad1-be23-b0571e399f9a">

**Comment by gdementen** [comment] 2024-09-07 18:44
Ok, I'll do that on a sandbox, just to ne sure. Thanks a lot for your help.

Le sam. 7 sept. 2024, 11:57, Felix Zumstein ***@***.***> a
écrit :

**Closed** 2024-09-19 15:12 UTC
