### ISSUE TITLE
Page break changes after saving

### ISSUE THREAD

**Issue by Pascal-PB** [xlwings/xlwings#2143] opened 2023-01-17 13:50 UTC
#### The page break is changed after opening and saving the file.

```python
# No error from Python

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)
![template](https://user-images.githubusercontent.com/122885517/212916736-94cf3841-59b2-4a57-a320-94c8b5da0a3e.PNG)
![test](https://user-images.githubusercontent.com/122885517/212916818-ff295009-a02b-421b-b066-fa7a7ed97c6c.PNG)

```python
# Your code here
import xlwings

file = xlwings.Book("template.xlsm")
sheet = file.sheets["Blad1"]

file.save("test.xlsm")

```

**Comment by fzumstein** [comment] 2023-01-17 17:33
Have you tried to open the workbook and save manually to see if it behaves the same? xlwings doesn't do anything with regards to page break, this looks to me as if Excel itself is doing this. As a workaround, you can always read and re-assign the print area via: https://docs.xlwings.org/en/stable/api.html#xlwings.main.PageSetup.print_area

**Comment by Pascal-PB** [comment] 2023-01-18 07:06
Yes, I have tried to open and save it manually. The page break stays as it was. It only changes when I use code.

**Comment by fzumstein** [comment] 2023-01-18 11:15
If you can upload the Excel file, I can look into it (but I don't think there's much I can do about it). Otherwise, just use the workaround as described above.

**Comment by Pascal-PB** [comment] 2023-01-18 12:07
The workaround works. So for now it will be fine but I would apriciate it if you take a look at the file to see if it also happens on your computer.

The original template has a lot of more sheets. On almost all sheets the page breaks changes.
[template.zip](https://github.com/xlwings/xlwings/files/10445843/template.zip)

**Comment by fzumstein** [comment] 2023-01-18 13:43
I tried with your file and couldn't replicate the issue. I suspect this is being caused by something else, but not by the save command. Closing this as non reproducible and working workaround.

**Closed by fzumstein** 2023-01-18 13:43 UTC

**Comment by Pascal-PB** [comment] 2023-01-18 13:47
Thank you very much for your time and workaround. I really appreciate it.
