### ISSUE TITLE
The problem with saving wb.save()

### ISSUE THREAD

**Issue by ProgrammSkill** [xlwings/xlwings#2441] opened 2024-05-20 06:59 UTC
When I try to save data, Windows Explorer opens with an open Excel file, the name of the file to save in the field came from somewhere (see screenshot). There is no such problem in the script on another computer, the Excel file also opens at the beginning, but there is no such problem when saving and closing the file. Why is this happening? The versions of Excel on two computers are the same.

```
wb = xw.Book(path_invoice, notify=False)
sheet = wb.sheets.active

for row in range(1, sheet.cells.rows.count):
    stop = False
    if not isinstance(sheet.cells(row, 2).value, (int, float)) and sheet.cells(row, 2).value is not None:
        if sheet.cells(row, 2).value == 'TOTAL AMOUNT/ ИТОГОВАЯ СУММА':
            x = sheet.cells(row + 3, 2).left 
            y = sheet.cells(row + 3, 2).top  

            image_supplier_signature = sheet.pictures.add(path_supplier_signature, left=x + 220, top=y + 80)
            img_supplier_stamp = sheet.pictures.add(path_supplier_stamp, left=x + 270, top=y + 30)

            for parameter_image in PICTURE_SIZES:
                if parameter_image['contract_number'] == contract_number:
                    image_supplier_signature.width = parameter_image['width_signature']
                    image_supplier_signature.height = parameter_image['height_signature']

                    img_supplier_stamp.width = parameter_image['width_stamp']
                    img_supplier_stamp.height = parameter_image['height_stamp']

            wb.save(path_invoice)
            wb.close()
```
![16feb72a-f87e-4869-b360-b8ab39c01465](https://github.com/xlwings/xlwings/assets/55989679/6773db51-7dc5-4961-9ead-f8c39cc9cacb)

**Comment by fzumstein** [comment] 2024-05-20 07:35
I've never seen this, so not sure what's happening. When you click on Save manually on this computer, does it work properly?

**Comment by ProgrammSkill** [comment] 2024-05-20 07:54
An error occurs when saving manually "Traceback (most recent call last):
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\main.py", line 677, in properties
    yield self
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\main.py", line 1164, in save
    self.impl.save(path, password=password)
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\_xlwindows.py", line 894, in save
    self.xl.SaveAs(
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A5CA5~1.NIK\AppData\Local\Temp\3\gen_py\3.12\00020813-0000-0000-C000-000000000046x0x1x9.py", line 46888, in SaveAs
    return self._oleobj_.InvokeTypes(3174, LCID, 1, (24, 0), ((12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (3, 49), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17), (12, 17)),Filename
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147023170, 'Сбой при удаленном вызове процедуры.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\script_formation_documents\main.py", line 68, in <module>
    data_form_invoice = invoiceDateExtractor(path_doc)  # получение данных из инвойса и конвертирование в PDF
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\script_formation_documents\invoice_data_extractor.py", line 170, in invoiceDateExtractor
    wb.save(path_invoice)
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\main.py", line 1163, in save
    with self.app.properties(display_alerts=False):
  File "C:\Program Files\PY\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\main.py", line 680, in properties
    setattr(self, attribute, value)
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\main.py", line 443, in display_alerts
    self.impl.display_alerts = value
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\_xlwindows.py", line 652, in display_alerts
    self.xl.DisplayAlerts = value
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\_xlwindows.py", line 161, in __setattr__
    return setattr(self._inner, key, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\xlwings\_win32patch.py", line 65, in __s
![Screenshot_39](https://github.com/xlwings/xlwings/assets/55989679/bc4c8cbb-f8a6-483d-9de0-53e94466002f)
etattr__
    d.__setattr__(attr, value)
  File "C:\projects\script_formation_documents\venv\Lib\site-packages\win32com\client\__init__.py", line 597, in __setattr__
    self._oleobj_.Invoke(*(args + (value,) + defArgs))
pywintypes.com_error: (-2147023174, 'Сервер RPC недоступен.', None, None)"

**Comment by ProgrammSkill** [comment] 2024-05-20 08:09
I understand that there is some kind of error with the RPC server. What kind of RPC server is it?

**Comment by ProgrammSkill** [comment] 2024-05-20 08:10
I understand that there is some kind of error with the RPC server. What kind of RPC server is it?

**Comment by fzumstein** [comment] 2024-05-20 08:11
By 'manually', I was referring to clicking the save button in Excel.

**Comment by ProgrammSkill** [comment] 2024-05-20 08:28
Now I tried it manually, everything was saved correctly, the explorer did not pop up, as it happens in my script

**Comment by fzumstein** [comment] 2024-05-20 08:56
In that case, I don't know what's happening. but you may be able to find more clues when stepping through the code:

https://github.com/xlwings/xlwings/blob/main/xlwings/main.py#L1133-L1164

and the Windows implementation:

https://github.com/xlwings/xlwings/blob/main/xlwings/_xlwindows.py#L850-L897

**Comment by fzumstein** [comment] 2024-12-09 15:45
@ProgrammSkill Would it be possible that this is caused by WindowsDefender or something similar?

**Comment by fzumstein** [comment] 2024-12-10 10:08
Ok, I've finally seen what you're doing: your are closing the workbook inside of the loop, so the second time around, the workbook doesn't exist anymore, which is why you're getting the `The RPC server is unavailable` error.

**Closed by fzumstein** 2024-12-10 10:08 UTC
