### ISSUE TITLE
Relative udf import from subdirectory

### ISSUE THREAD

**Issue by olejonny** [xlwings/xlwings#1281] opened 2020-03-20 13:10 UTC
#### Describe your issue (incl. Traceback!)

How can I import udf from subdirectory? E.g. :
mainfolder
----myexcelfile.xlsm (including .conf sheet)
----myexcelfile.py
----udf_folder
--------udf.py
----modules
--------some_python_module.py

When I try to use the conf sheet and the UDF Modules cell with : ./udf/udf , I get Typeerror: the "package" argument is required to perform a relative import.
I'm not a professional programmer, just an engineer. So I need this almost like I am 5 :)

**Comment by fzumstein** [comment] 2020-03-20 13:54
Unfortunately, this is currently not possible. As this is a duplicate of https://github.com/xlwings/xlwings/issues/883, i am closing this issue. You could, however, use something like `%USERPROFILE%\...` in your PYTHONPATH. Note that the UDF Module is only `udf` in your example, no matter where it is - you would add the rest of the path to the PYTHONPATH.

**Closed by fzumstein** 2020-03-20 13:54 UTC
