### ISSUE TITLE
Cannot import module "System" properly when execute using xlwings

### ISSUE THREAD

**Issue by JargonPiHarston** [xlwings/xlwings#1765] opened 2021-11-16 17:30 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
Was using Windows 7. The PC was just having an upgrade to Windows 10 on the weekend. I suspect that this is definitely part of the issue.

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
xlwings==0.25.0
python==3.7.5
Excel 2019 64-bit

#### Describe your issue (incl. Traceback!)
Can't seem to import the module named 'System' properly. Normally. I use the package `pythonnet ` in order to use some of the internally developed C# DLL. Has been working fine until the system was upgraded to Windows 10. I am posting this here because this only happens when the code is executed through xlwings.

One important thing to note is that the drive `G:` you see in all the text below is a network shared drive. All the tools, e.g., conda env, xlwings plugin, excel workbook, etc. is on there. Again, everything works fine until the Windows 10 upgrade.

The code attached below works just fine under these settings.
- Executing on Pycharm Interactive Console using the same conda environment.
- Executing the code through `cmd` by activating the conda env, then execute the script.
- Toggling `Debug UDFs` mode on, start the debugging server on Pycharm, then `Import Functions`.

Obviously the script below is made to replicate the real code that is deployed in the real application. However I have tested the real app itself and it also only works under the three above conditions, but not the xlwings without `Debug UDFs`. I am currently relying on the Debug UDFs mode to get things working. 

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import sys
from pprint import pprint
print("==== Printing sys.path before importing anything, press ENTER to print =======")
input()
pprint(sys.path)
import os
print("os.getcwd() = ", os.getcwd())
input()
import clr
print('clr.FindAssembly : ', clr.FindAssembly('System'))
input()
import System
print("Import System successfully!")
print("System file location :", System.__file__)
input()
print(print(f"Printing date from System.DateTime object: {x.Year}-{x.Month}-{x.Day}"))

def main():
    pass

```

Now if we create a new blanksheet containing 'xlwings.conf' sheet with the following configurations,

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<body link="#0563C1" vlink="#954F72">

Conda   Path | G:\Pricing Spreadsheet\Python   Pricing\conda-pricing
-- | --
Conda Env | base
Show Console | TRUE
PYTHONPATH | G:\Pricing Spreadsheet\Python Pricing\Quant   Engine\excel_models

</body>

</html>

, then press RunPython from xlwings ribbon, I would get an error popup below.

#### Trackback from RunPython in Excel
``` python
---------------------------
Error
---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "g:\pricing spreadsheet\python pricing\quant engine\pythonnet_test.py", line 16, in <module>
    print(print(f"Printing date from System.DateTime object: {x.Year}-{x.Month}-{x.Day}"))
NameError: name 'x' is not defined
Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------
```

The console right before getting the error popup:

```
'\\PT------P02\p------e\ji-----o'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
==== Printing sys.path before importing anything, press ENTER to print =======

['g:\\pricing spreadsheet\\python pricing\\xlwings',
 'g:\\pricing spreadsheet\\python pricing\\quant engine\\pythonnet_test.zip',
 'g:\\pricing spreadsheet\\python pricing\\quant engine\\excel_models',
 'g:\\pricing spreadsheet\\python pricing\\quant engine',
 'g:\\pricing spreadsheet\\python pricing\\xlwings\\xlwings 0.25.0.zip',
 '',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\python37.zip',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\DLLs',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\lib',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\lib\\site-packages',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\win32',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\win32\\lib',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\Pythonwin']
os.getcwd() =  C:\Windows

clr.FindAssembly :  G:\Pricing Spreadsheet\Python Pricing\conda-pricing\System.dll

Import System successfully!
System file location : None
```

Note that the value printed on last line `System file location: None` is unexpected. Here's the console from executing the snippet using `cmd`. The console output in other two settings show similar messages and execute successfully as well.

```
==== Printing sys.path before importing anything, press ENTER to print =======
['G:\\Pricing Spreadsheet\\Python Pricing\\Quant Engine',
 'C:\\Program Files\\JetBrains\\PyCharm Community Edition '
 '2021.2.3\\plugins\\python-ce\\helpers\\pydev',
 'G:\\Pricing Spreadsheet\\Python Pricing\\Quant Engine',
 'C:\\Program Files\\JetBrains\\PyCharm Community Edition '
 '2021.2.3\\plugins\\python-ce\\helpers\\third_party\\thriftpy',
 'C:\\Program Files\\JetBrains\\PyCharm Community Edition '
 '2021.2.3\\plugins\\python-ce\\helpers\\pydev',
 'C:\\Users\\jirappoo\\AppData\\Local\\JetBrains\\PyCharmCE2021.2\\cythonExtensions',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\python37.zip',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\DLLs',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\lib',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing',
 'G:\\Pricing Spreadsheet\\Python Pricing\\conda-pricing\\lib\\site-packages',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\win32',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\win32\\lib',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\Pythonwin',
 'G:\\Pricing Spreadsheet\\Python '
 'Pricing\\conda-pricing\\lib\\site-packages\\IPython\\extensions']
os.getcwd() =  G:\Pricing Spreadsheet\Python Pricing\Quant Engine
clr.FindAssembly :  G:\Pricing Spreadsheet\Python Pricing\conda-pricing\System.dll
Import System successfully!
System file location : C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
Printing date from System.DateTime object: 2021-11-17

Process finished with exit code 0
```

Notice that the System file location now is not `None`, but showing the System module as the .dll from the GAC directory, despite `clr.FindAssembly('System')` shows that (another) DLL dir is at `G:\Pricing Spreadsheet\Python Pricing\conda-pricing\System.dll`. This is the expected behavior as it should be getting the DLL in GAC first before PATH. However, under the xlwings deployment setting, Python completely fails to locate the DLL, missing even the duplicated one on `G:\Pricing Spreadsheet\Python Pricing\conda-pricing\System.dll`

So right now I have no clue what's going on.

Thanks in advance.

**Comment by fzumstein** [comment] 2021-11-17 07:59
Since you mention pythonnet, you may want to have a look at https://github.com/xlwings/xlwings/issues/997. Also, I assume you were on an older version of xlwings on Win7? I'd first try to use the same version to make sure it's not regression that was introduced in a later version.

**Comment by JargonPiHarston** [comment] 2021-11-23 06:51
Indeed, I was using xlwings==0.24.9 before on Win7. I just made an update to 0.25.0 and also updating pythonnet to the latest version to see if anything is solved. But the issue persisted on both versions.

I was just able to roughly identify and mitigate the problem (for now...). I was hypothesizing that `sys.path` looks a bit weird, so perhaps that messes with some import mechanism used by the clr module. Since I expect the module System to be found in the GAC regardless of what `sys.path` is anyway, I tried simply assign `sys.path` as an empty list then import System module and it just works somehow. So the dirty fix that I made is exactly that; empty out `sys.path`, import System, restore the original value. Everything works fine now.

Before that I did all that, I actually did some digging into the xlwings module on the VBA side to see exactly what are the differences between running with xlwings from Excel and other settings and already saw that xlwings did front-appending the `sys.path` because executing the Python script. So I am suspecting that is the root cause of the problem for me and my execution environment. However, I am not so sure and even if it does, I have no idea how or why. Perhaps you can provide some insights on this.

**Comment by fzumstein** [comment] 2021-11-23 08:05
The only thing that xlwings does is prepend `sys.path` with the path of the workbook's folder and any of the directories you may have put in the PYTHONPATH xlwings setting. From your printed output, I can see that you use the folder name `xlwings`. It's almost always a bad idea to call a directory the same as a Python package.

**Comment by fzumstein** [comment] 2022-05-21 18:02
Closing this but feel free to reopen if you still need help here.

**Closed by fzumstein** 2022-05-21 18:02 UTC
