### ISSUE TITLE
Multiple SharePoint sites synchronized: delayed start of xlwings

### ISSUE THREAD

**Issue by tstone-1** [xlwings/xlwings#1834] opened 2022-02-15 07:43 UTC
#### Describe your issue (incl. Traceback!)

I've had only one SharePoint resource synchronized to C:\Users\MYNAME\MYCOMPANY\SITE1 until yesterday. I've created a number of xlwings-based scripts for SITE1. After having added another site which synchronizes to C:\Users\MYNAME\MYCOMPANY\SITE2, my existing xlwings scripts for SITE1 became horribly slow. I've set the SHAREPOINT_WIN environment variable of my Windows user to C:\Users\MYNAME\MYCOMPANY\SITE1. SITE2 does contain a larger amount of data (~40,000 directories, ~150,000 files). The initiation time (time which passes from calling the script and first output to cmd.exe) went from 2-3 seconds to ~15 seconds.

As I understand [the getting started site](https://docs.xlwings.org/en/latest/onedrive_sharepoint.html), xlwings scans the whole SharePoint directory for the Excel document requested. Is this really necessary? I'm always using an absolute path to the Excel file when calling `xw.Book()`.

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

n.a.

**Comment by fzumstein** [comment] 2022-02-15 11:43
There is improvement on the way, and as such this is a dupe of https://github.com/xlwings/xlwings/issues/1829 and therefore closing this.

**Closed by fzumstein** 2022-02-15 11:43 UTC
