### ISSUE TITLE
Text format for strings with view()

### ISSUE THREAD

**Issue by StefRe** [xlwings/xlwings#2247] opened 2023-05-03 14:22 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 10

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.28.7, Office 365, Python 3.10

#### Describe your issue (incl. Traceback!)
When displaying an object using `view`, Excel applies the "Standard" format which implies undesired conversions when displaying strings completely made up of digits (leading zeros are lost) or strings that could be interpreted as dates etc.
```python
xw.view(['012', '1/2'])
```
yields 
![grafik](https://user-images.githubusercontent.com/19879328/235939253-e2f8397f-5e22-445f-bef1-e5aacf903b53.png)
(German locale)

#### Proposed action
I understand that `view` is meant for interactive use (quick and dirty), but couldn't we at least for strings set the format in Excel according to the Python type?

For a single string object it would be as easy as adding 
```python
if isinstance(obj, str):
    sheet["A1"].number_format = '@'
``` 
after

https://github.com/xlwings/xlwings/blob/8be1adee5d619d16bc66cf115fd1f72d732f4d1d/xlwings/main.py#L4728-L4728

I'm not sure how complex this can get to cover all possible types with built in converters or if this fix should be done elsewhere, so this is just to illustrate the issue and the desired behavior.

**Comment by fzumstein** [comment] 2023-05-04 10:51
This isn't specific to `view` and a duplicate of https://github.com/xlwings/xlwings/issues/436 and https://github.com/xlwings/xlwings/issues/36. For the regular API, there's also formatters nowadays: https://docs.xlwings.org/en/latest/converters.html#formatter that could be useful for this task. For single values, the easiest solution is probably to prepend them with a `'`.

**Closed by fzumstein** 2023-05-04 10:51 UTC

**Comment by fzumstein** [comment] 2023-05-04 10:57
I'll take back the comment about formatters: they wouldn't help here as they get applied after writing to Excel.

**Comment by StefRe** [comment] 2023-05-04 12:47
Thanks for the reply, I didn't see that it's a duplicate because I searched specifically for `view` (I was at first under the impression that the Object Model would behave differently (like `pd.Series(['012', '1/2']).to_excel('test.xlsx')` that transfers the formats correctly) which is of course not the case as the `view` uses the Object Model under the hood).

Unforturnately, prepending an apostroph is not an option in my case as I need to further process the values in Excel and I'd first need to format the cells and remove the apostroph in Excel.
