### ISSUE TITLE
Cannot get xlwings to run a function from excel Run-time error 13 and 429

### ISSUE THREAD

**Issue by julioolvera1** [xlwings/xlwings#1436] opened 2020-10-13 12:39 UTC
#### Versions of xlwings=0.20.7, Excel=365 and Python=3.7.9 

I am having some problems with xlwings even after removing and reinstalling several times.

I created a completely new anaconda environment in Windows: `excelPy`

I installed the latest version of xlwings using:

`conda install -c conda-forge xlwings `

and got version 0.20.7

I installed the xlwings addin

`xlwings adding install`

I created a new project:

`xlwings quickstart myproject`

Opened the xlsm file, enabled content and tried "Run main", got:

**Run-time error '429' ActiveX component can't create object**

My xlwings tab looks as follows: 

![image](https://user-images.githubusercontent.com/30075340/95861380-4113d000-0d59-11eb-973c-fd99203e80cf.png)

Interpreter: C:\Users\username\AppData\Local\Continuum\anaconda3\pythonw
Conda Path: C:\Users\username\AppData\Local\Continuum\anaconda3 
Conda Env: excelPy

My conf file is stored in `C:\Users\username\.xlwings\xlwings.conf` and looks like:

"CONDA ENV","excelPy" "INTERPRETER_WIN","C:\Users\username\AppData\Local\Continuum\anaconda3\pythonw" "CONDA PATH","C:\Users\username\AppData\Local\Continuum\anaconda3" "SHOW CONSOLE","False"

Also, if I tick show console I get:

![image](https://user-images.githubusercontent.com/30075340/95861420-51c44600-0d59-11eb-897e-a964d124d6b1.png)

When I enter the references in VBA I got this:

![image](https://user-images.githubusercontent.com/30075340/95861424-5557cd00-0d59-11eb-9261-27b16e199d5c.png)

Also, if I start python and open a book through xlwings it works:

```
import xlwings as xw

xw.Book()

out: <Book [Book1]>
```

So it's only when running python scripts from VBA

Does anyone knows what is wrong with the installation?

Thanks a lot!

**Comment by fzumstein** [comment] 2020-10-13 12:44
From your activated `excelPy` env, can you run the following:

```
xlwings config create --force
```

This will reconfigure your settings with the `excelPy` env. Please try again and let me know how it works.

**Comment by julioolvera1** [comment] 2020-10-13 14:17
Thank you for your reply @fzumstein 

As suggested, within the environment `excelPy ` I ran:
`xlwings config create --force`

Then:
`xlwings quickstart myproject_test_v4`

I opened `myproject_test_v4.xlsm`

Then Run main and got Run-time error 429, ActiveX component can't create object

**Comment by julioolvera1** [comment] 2020-10-13 16:39
I think the problem might be somewhere here:
![image](https://user-images.githubusercontent.com/30075340/95889978-12a6ec80-0d7b-11eb-837d-f5c0440e9c24.png)

**Comment by fzumstein** [comment] 2020-10-13 22:10
This is actually a duplicate of https://github.com/xlwings/xlwings/issues/1134, I am closing this issue: can you please continue there? Thanks.

**Closed by fzumstein** 2020-10-13 22:10 UTC
