### ISSUE TITLE
Named range not pulling correctly

### ISSUE THREAD

**Issue by dharlan-ihi** [xlwings/xlwings#2372] opened 2024-01-03 22:45 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
macOS Sonoma 14.2.1

#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.30.13, Microsoft 365 Excel 16.80, Python 3.9.18

#### Describe your issue (incl. Traceback!)
There is a named range called 'design_buffers' which contains 3 separate cells (BB109, BB111, BB113).  The error below in the traceback occurs when iterating over the values of this named range.  Printing this range.value would just return the contents of BB109.

However, if I change the named range to reference "BB111:BB113, BB109" the error does not occur and it correctly pulls in the values to iterate over.  However, this is not desirable as I do not want to include the value in BB112 as part of the named range.

Note that the values in 'design_buffers' are percentages.

```python
# Your traceback here
Traceback (most recent call last):
  File "/Users/.../design_automation.py", line 289, in <module>
    automate_design()
  File "/Users/.../design_automation.py", line 140, in automate_design
    automate_circuit_design(sht, 'battery_limited')
  File "/Users/.../design_automation.py", line 87, in automate_circuit_design
    all(x > 1.01 for x in sht.range('design_buffers').value):
TypeError: 'float' object is not iterable
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

Python code below, sample workbook attached.

```python
wb = xw.Book("/Users/.../named range error.xlsm")
sht = wb.sheets['Sheet1']

print(sht.range('combined_cells').value)
# [0.971712408271127, 3.931132920025363, 0.971712408271127]
print(sht.range('individual_cells').value)
# 3.931132920025363

for x in sht.range('combined_cells').value:
    print(x)
# 0.971712408271127
# 3.931132920025363
# 0.971712408271127

for x in sht.range('individual_cells').value:
    print(x)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object is not iterable

```

[named range error.xlsx](https://github.com/xlwings/xlwings/files/13824119/named.range.error.xlsx)

**Comment by fzumstein** [comment] 2024-01-04 14:13
Hi, this isn't an issue with the named range but because xlwings doesn't currently have support for multiple ranges. As such it's a dupe of https://github.com/xlwings/xlwings/issues/595

**Closed by fzumstein** 2024-01-04 14:13 UTC
