### ISSUE TITLE
xlwings.XlwingsError: Make sure to have "pywin32", a dependency of xlwings, installed

### ISSUE THREAD

**Issue by bebeksaurus** [xlwings/xlwings#2314] opened 2023-08-12 15:49 UTC
Dear All,

I used Python 3.11 and Xlwings 0.30.10 and pywin32 -306, excel 2019, run from windows 10, and this is my python script :

wb  =   xw.Book('Testkirim.xlsx').

But, when i run that code, there are message like this:

Traceback (most recent call last):
  File "C:\Python\script\Kirim email notif.py", line 32, in <module>
    wb  =   xw.Book('Testkirim.xlsx')
  File "C:\Python\Lib\site-packages\xlwings\main.py", line 912, in __init__
    for app in apps:
  File "C:\Python\Lib\site-packages\xlwings\main.py", line 256, in __iter__
    for app in self.impl:
  File "C:\Python\Lib\site-packages\xlwings\main.py", line 5167, in impl
    raise XlwingsError(
xlwings.XlwingsError: Make sure to have "pywin32", a dependency of xlwings, installed.

How to fix this problem. Please give me an advice to solve this issue. thx

#### Describe your issue (incl. Traceback!)

```python
# Your traceback here

```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
# Your code here

```

**Comment by fzumstein** [comment] 2023-08-14 06:10
This is a duplicate of https://github.com/xlwings/xlwings/issues/2276. Please see instructions there.

**Closed by fzumstein** 2023-08-14 06:10 UTC
