### ISSUE TITLE
Excel Tables overwriting formulas via .update()

### ISSUE THREAD

**Issue by Matt-Greer** [xlwings/xlwings#2113] opened 2022-12-06 22:23 UTC
#### When I create a dataframe with formulas in it and then .update an excel structured table with that dataframe, the first row formulas overwrite all formulas in that column.

wb.app.api.Application.AutoCorrect.AutoFillFormulasInLists = False does change the autocorrect option, but it it seems to have no effect on the table and the equations on the top row overwrite any equations in the same column.

```python
# Your traceback here
There is no traceback, no error is listed.

Thank you for your help!

**Comment by fzumstein** [comment] 2022-12-07 08:18
Please add some screenshots of how it's behaving and what you'd expect instead.

**Comment by Matt-Greer** [comment] 2022-12-08 21:39
![Screenshot 2022-12-08 143538](https://user-images.githubusercontent.com/90704736/206572545-30da606c-b59d-49ef-a28b-52f9c7de8fa4.png)

Formulas are determined in the function and are added to a dataframe.  The df is used to ".update" the table in excel.  Everything works as it should until there is a formula in the top row, at which point Excel overwrites all formulas in the same column with the formula in the cell in the top row.  I double checked in Excel to make sure that `AutoFillFormulasInLists` is not checked, but it still happens.  I also included **wb.app.calculation = 'manual'** but still, the formulas are overwritten incorrectly.

Thank you for your help!

-Matt

**Comment by fzumstein** [comment] 2022-12-08 22:06
Hi Matt, I think what you see is a core feature of Excel tables (same formulas in each column), it has nothing to do with AutoCorrect. I would need a minimal reproducible sample (Excel file and Python code) if you still think this is an issue with xlwings.

**Comment by slmg** [comment] 2023-04-21 09:48
Could this issue please be re-open @fzumstein ? This is an issue with xlwings as Excel allows to enable or disable this AutoCorrect option ( in which case it is possible to have a column within a table containing multiple formulas). The problem is **updating a table with xlwings always update all formulas, even when this option is disabled.**

Steps to reproduce.

1. Disable Excel's formulas auto-correct behaviour

    ```python
    > wb.app.api.AutoCorrect.AutoFillFormulasInLists = False
    ```

1. Create a dataframe with a column containing heterogenous formulas

    ```python
    > df = pd.DataFrame(
        {"col1": [1, 2], "col2": [100, 200], "col3": ["=[@col1]", "=[@col2]"]}
    )
    > print(df)
       col1  col2      col3
    0     1   100  =[@col1]
    1     2   200  =[@col2]
    ```

1. Create an Excel table and update it with our this `df`.

    ```python
    > mytable = sheet.tables.add(source=sheet.range("B2"), name="mytable")
    > mytable.update(df, index=False)
    ```

1. Notice the Excel table contains the below, which is wrong.

    ```txt
    col1  col2      col3
       1   100  =[@col1]
       2   200  =[@col1]
    ```

1. Manually update one of the cell in the Excel table to `=[@col2]` and see it works fine, which shows Excel allows this behaviour in tables, which implies it should be achievable with xlwings.

    ```txt
    col1  col2      col3
       1   100  =[@col1]
       2   200  =[@col2]
    ```

Thanks

**Comment by fzumstein** [comment] 2023-04-21 10:50
@slmg thanks for the reproducible steps, I'll try to look into it.

**Comment by fzumstein** [comment] 2023-04-22 14:33
This seems to be a bug/feature in COM. Running this code in VBA results in the same behavior:

```vb
Sub Test()
    Application.AutoCorrect.AutoFillFormulasInLists = False
    Dim myArray(1 To 2, 1 To 3) As Variant
    
    myArray(1, 1) = 1
    myArray(1, 2) = 100
    myArray(1, 3) = "=[@col1]"
    myArray(2, 1) = 2
    myArray(2, 2) = 200
    myArray(2, 3) = "=[@col2]"
    
    ' Write the values of the array to range A1:C2
    Range("B3:D4").Value = myArray

End Sub
```

I don't think there's much I can do about this. You could, however, use standard cell formulas instead of structured references to avoid this.

Closing this again as it's the behavior of COM.

**Closed by fzumstein** 2023-04-22 14:33 UTC

**Comment by fzumstein** [comment] 2023-04-22 22:23
This behavior is confirmed here: https://stackoverflow.com/questions/70298198/table-autofilling-formula-even-with-application-autocorrect-autofillformulasinli

**Comment by slmg** [comment] 2023-04-23 12:44
Thank you for investigating. Yes I tried to use standard cell formulas within a table and saw it led to the same behaviour. It is a pity and clearly a bug IMO, as it forces to completely abandon tables and use explicit cell references instead. A lot more convoluted, fragile and less readable :disappointed:.

**Comment by fzumstein** [comment] 2023-04-23 12:49
In my experience, Excel tables are only helpful if you use them as a database. As such, it's ok to not allow different formulas within a column. You could add an additional column with the other formula?

**Comment by slmg** [comment] 2023-04-23 14:57
I find Excel tables helpful mainly because it's the only way to leverage the structured reference syntax. In the context of pandas/xlwings it's great since we can manipulate data without worrying about row indexing and column ordering output. And I liked xlwings's table api to read/write tables.

To detail the use case that prompted me to come back to this issue, I am storing the result of multi-dimensional linear regression within a table. I have a column `y` which contain the following formula: `=SUM(x1_coef*x1_last, x2_coef*x2_last, ...)`. Depending of the study, there can be n dimension, therefore this formula must be variable and point to `x1..xn` columns. And I cannot pre-compute in Python because the `xn_last` columns contain live-updated data.

**Comment by fzumstein** [comment] 2023-04-23 16:15
Ok thanks for sharing. For the record, I've just tried with Office Scripts, and it shows the same behavior...
