### ISSUE TITLE
Automation Error 440 - Issue with "Import Functions" & UDFs called in VBA

### ISSUE THREAD

**Issue by capitalinc** [xlwings/xlwings#1686] opened 2021-07-29 16:38 UTC
#### The screenshot below gives insight into what error I am encountering. I played around with the setup a bit - changing variable names, function calls, etc. However, I cannot resolve the issue that as long as I am calling a UDF from VBA [ Call wrapper_reprice_struc(i, s1_col) ], I get the 440 Error every time I re-import my python script with "Import Functions" after having done some changes. The error originates from xlwings, and I get stuck with two "xlwings_udfs" modules (see screenshot).

I can resolve the error by manually deleting the "xlwings_udfs1" module (as I get a duplicate error if I don't), and my updated python script with full functionality is available.

Another way to completely avoid the error is to go through "RunPython" - when I use exactly the same function in this way, I get no error at all when re-importing with "Import Functions".

I am hoping this information will help resolve this issue.

![440error_xlwings](https://user-images.githubusercontent.com/48288493/127529264-c010c026-0d9a-4886-8f27-dc4382c9c0b7.PNG)

```python
# Your traceback here

```

#### This is the python function I am calling (it keeps on going with similar code thereafter):

```python
# 
@xw.sub
def struc_reprice_xl(s_row,s_cols):
    wb = xw.Book.caller()
    
    struc_pricer_xl(wb,0,s_row,s_col)
    #struc_pricer_strips_xl(wb,0,s_row,s_cols)
    
    
def struc_pricer_xl(wb,i,s1_row,s1_col):
    wb.sheets["Structures"].range((s1_row+i,s1_col)).color = None
    wb.sheets["Structures"].range((s1_row+i,s1_col+17),(s1_row+i+1,s1_col+26)).clear_contents()
    if wb.sheets["Structures"].range((s1_row+i,s1_col+2)).value is None:
        pass
    else:
        # Tenor
        t = wb.sheets["Structures"].range((s1_row+i,s1_col+2)).value.strip()
        c = wb.sheets["Structures"].range((s1_row+i,s1_col+3)).value.strip().upper()
...

```

**Comment by fzumstein** [comment] 2022-05-21 18:09
sorry for slow response but I didn't have any ideas what could be going on. Since it's been a while, I'll close this, but feel free to reopen with a minimal sample to reproduce (Excel and Python).

**Closed by fzumstein** 2022-05-21 18:09 UTC
