### ISSUE TITLE
Xlwings / Read Time-Cell?

### ISSUE THREAD

**Issue by Rapid1898-code** [xlwings/xlwings#2105] opened 2022-11-26 10:04 UTC
Hello - i have an excel-sheet with a column with time-values in the format "hh:mm:ss"

When i read this value with xlwings with eg. this code:

```
wb = xw.Book (fn)  
ws = wb.sheets[0]  
wTime = ws["B1"].value
```

I don´t get the time in the form "18:52:19" I get instead 0.7863310185185185 as a float

How can i read this time to python eg. as a string? Or other datetime format which i can work with? (but i can´t simply format the cell in excel to text - this has to stay with "hh:mm:ss"-formating)

**Comment by fzumstein** [comment] 2022-11-26 14:18
that's a duplicate of https://github.com/xlwings/xlwings/issues/86, i.e. currently not handled. Same comments apply as https://github.com/xlwings/xlwings/issues/2003.

Also, in the future please fill in the issue template so I know on which platform you are etc.

**Closed by fzumstein** 2022-11-26 14:18 UTC
