### ISSUE TITLE
Exception when union ranges

### ISSUE THREAD

**Issue by Roey1234560** [xlwings/xlwings#2353] opened 2023-11-12 16:46 UTC
OS Windows 10
xlwings 0.30.12, Office 2016, Python 3.9.1

Hi,
I'm trying to select multiple ranges (not adjacent), but after certain amount of ranges (I think I count 29) I get the following exception:

```python
Traceback (most recent call last):
  File "C:\...\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\...\lib\site-packages\xlwings\main.py", line 1438, in range
    return Range(impl=self.impl.range(cell1, cell2))
  File "C:\...\lib\site-packages\xlwings\_xlwindows.py", line 1025, in range
    xl1 = self.xl.Range(arg1)
  File "C:\...\lib\site-packages\xlwings\_xlwindows.py", line 122, in __call__
    v = self.__method(*args, **kwargs)
  File "C:\...\AppData\Local\Temp\gen_py\3.9\00020813-0000-0000-C000-000000000046x0x1x9.py", line 45830, in Range
    ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)


This is the code I'm using:
wb = xw.Book(xl_dir)
sheet1 = wb.sheets[2]
rng_str = 'G21:U21,G24:U24,G27:U27,G30:U30,G33:U33,G36:U36,G39:U39,G42:U42,G45:U45,G48:U48,G51:U51,G54:U54,G57:U57,G60:U60,G63:U63,G88:U88,G91:U91,G94:U94,G97:U97,G100:U100,G103:U103,G106:U106,G109:U109,G112:U112,G115:U115,G118:U118,G121:U121,G124:U124,G127:U127,G130:U130,G155:U155,G158:U158,G161:U161,G164:U164,G167:U167,G170:U170,G173:U173,G176:U176,G179:U179,G182:U182,G185:U185,G188:U188,G191:U191,G194:U194,G197:U197,G222:U222,G225:U225,G228:U228,G231:U231,G234:U234,G237:U237,G240:U240,G243:U243,G246:U246,G249:U249,G252:U252,G255:U255,G258:U258,G261:U261,G264:U264,G289:U289,G292:U292,G295:U295,G298:U298,G301:U301,G304:U304,G307:U307,G310:U310,G313:U313,G316:U316,G319:U319,G322:U322,G325:U325,G328:U328,G331:U331,G356:U356,G359:U359,G362:U362,G365:U365,G368:U368,G371:U371,G374:U374,G377:U377,G380:U380,G383:U383,G386:U386,G389:U389,G392:U392,G395:U395,G398:U398,G423:U423,G426:U426,G429:U429,G432:U432,G435:U435,G438:U438,G441:U441,G444:U444,G447:U447,G450:U450,G453:U453,G456:U456,G459:U459,G462:U462,G465:U465'

sheet1.range(rng_str).select()
```

**Comment by fzumstein** [comment] 2023-11-12 16:50
xlwings currently doesn't officially support multi-ranges...

**Comment by fzumstein** [comment] 2024-01-04 14:12
Closing this as dupe of https://github.com/xlwings/xlwings/issues/595

**Closed by fzumstein** 2024-01-04 14:12 UTC
